-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') as PUBLISHED_DATE from BOOK inner JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
where BOOK.CATEGORY = '경제'
order by PUBLISHED_DATE asc;