-- 코드를 작성해주세요
select ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST),1), 'km') TOTAL_DISTANCE, CONCAT(ROUND(AVG(D_BETWEEN_DIST),2), 'km') AVERAGE_DISTANCE
from SUBWAY_DISTANCE
group by 1
order by SUM(D_BETWEEN_DIST) desc;