-- 코드를 작성해주세요
select C.ID, C.GENOTYPE, C.PARENT_GENOTYPE
from (
    select A.ID, A.PARENT_ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE
    from ECOLI_DATA as A
    left join ECOLI_DATA as B
    on A.PARENT_ID = B.ID
) AS C
where C.GENOTYPE & C.PARENT_GENOTYPE = C.PARENT_GENOTYPE
ORDER BY C.ID